### PR TITLE
cleanup alignment

### PR DESCRIPTION
**Pull request by RobLui**
Alignment on newly added span :)

### CODE REVIEW

**Comment by diomed** [comment]
please don't do this. my code might not align properly, but all your contributions so far are code alignment.
what this theme really needs is some code improvement, if you will.

If  you know how to add taxonomy, - issue I requested help with, please do.
Also, if you know how to add gray area on bottom of item : https://demo.ghost.io/themes/
be my guest. 
If you wanna add any actual code improvement that works IT WILL be merged.
Indenting is only important in YAML, as far as I'm concerned.

**Comment by diomed** [comment]
forgot to mention - subscribe parts of the page also won't be merged,
they're left out deliberately

**Comment by RobLui** [comment]
Ok ;) I’lk check it out later tonighy if I’m able to add your requested features ;)

**Comment by RobLui** [comment]
Forgot to ask, what was the item you wanted a grey part in? Something like this? or .. where? :) 
schermafbeelding 2018-11-17 om 21 32 15

**Comment by diomed** [comment]
no. there is an area in blog item, above the footer, where two summary cards are placed. 
that area should be light gray, as it is in original link I sent you.

**Pull request closed without merging**
